In [26]:
import pandas as pd

# Load the file
df = pd.read_csv('data1.csv')

# View the first 5 rows
df.head()

         date  number_of_strikes center_point_geom
0  2018-01-03                194     POINT(-75 27)
1  2018-01-03                 41   POINT(-78.4 29)
2  2018-01-03                 33   POINT(-73.9 27)
3  2018-01-03                 38   POINT(-73.8 27)
4  2018-01-03                 92     POINT(-79 28)

In [27]:
df.tail()

            date  number_of_strikes  center_point_geom
9995  2018-02-07                111  POINT(-91.7 31.5)
9996  2018-02-07                111  POINT(-91.6 31.5)
9997  2018-02-07                 86  POINT(-91.5 31.5)
9998  2018-02-07                101  POINT(-91.4 31.5)
9999  2018-02-07                 85  POINT(-90.4 31.6)

In [28]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [29]:
df.duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool>

In [30]:
print(df.duplicated().sum())

0

In [31]:
df.describe()

       number_of_strikes
count       10000.000000
mean           80.931800
std            88.298061
min            23.000000
25%            34.000000
50%            50.000000
75%            90.000000
max          1611.000000

In [32]:
df["center_point_geom"].head()

0      POINT(-75 27)
1    POINT(-78.4 29)
2    POINT(-73.9 27)
3    POINT(-73.8 27)
4      POINT(-79 28)
Name: center_point_geom, dtype: str

In [33]:
df.columns

Index(['date', 'number_of_strikes', 'center_point_geom'], dtype='str')

In [34]:
df.to_numpy()

array([['2018-01-03', 194, 'POINT(-75 27)'],
       ['2018-01-03', 41, 'POINT(-78.4 29)'],
       ['2018-01-03', 33, 'POINT(-73.9 27)'],
       ...,
       ['2018-02-07', 86, 'POINT(-91.5 31.5)'],
       ['2018-02-07', 101, 'POINT(-91.4 31.5)'],
       ['2018-02-07', 85, 'POINT(-90.4 31.6)']],
      shape=(10000, 3), dtype=object)

In [35]:
df.head()

         date  number_of_strikes center_point_geom
0  2018-01-03                194     POINT(-75 27)
1  2018-01-03                 41   POINT(-78.4 29)
2  2018-01-03                 33   POINT(-73.9 27)
3  2018-01-03                 38   POINT(-73.8 27)
4  2018-01-03                 92     POINT(-79 28)

In [36]:
df.describe()

       number_of_strikes
count       10000.000000
mean           80.931800
std            88.298061
min            23.000000
25%            34.000000
50%            50.000000
75%            90.000000
max          1611.000000

In [37]:
df.head()

         date  number_of_strikes center_point_geom
0  2018-01-03                194     POINT(-75 27)
1  2018-01-03                 41   POINT(-78.4 29)
2  2018-01-03                 33   POINT(-73.9 27)
3  2018-01-03                 38   POINT(-73.8 27)
4  2018-01-03                 92     POINT(-79 28)

In [38]:
df.head().transpose()

,0,1,2,3,4
date,2018-01-03,2018-01-03,2018-01-03,2018-01-03,2018-01-03
number_of_strikes,194,41,33,38,92
center_point_geom,POINT(-75 27),POINT(-78.4 29),POINT(-73.9 27),POINT(-73.8 27),POINT(-79 28)

In [39]:
excel_df = df.head()

In [40]:
excel_df

         date  number_of_strikes center_point_geom
0  2018-01-03                194     POINT(-75 27)
1  2018-01-03                 41   POINT(-78.4 29)
2  2018-01-03                 33   POINT(-73.9 27)
3  2018-01-03                 38   POINT(-73.8 27)
4  2018-01-03                 92     POINT(-79 28)

In [16]:
pip install openpyxl

Requirement already satisfied: openpyxl in C:\data science\class_room\venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\data science\class_room\venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
excel_df.to_excel("data_head.xlsx" , index = False)

In [42]:
test_df = df.head(20)

test_df

          date  number_of_strikes center_point_geom
0   2018-01-03                194     POINT(-75 27)
1   2018-01-03                 41   POINT(-78.4 29)
2   2018-01-03                 33   POINT(-73.9 27)
3   2018-01-03                 38   POINT(-73.8 27)
4   2018-01-03                 92     POINT(-79 28)
5   2018-01-03                119     POINT(-78 28)
6   2018-01-03                 35   POINT(-79.3 28)
7   2018-01-03                 60   POINT(-79.1 28)
8   2018-01-03                 41   POINT(-78.7 28)
9   2018-01-03                119   POINT(-78.6 28)
10  2018-01-03                107   POINT(-78.5 28)
11  2018-01-03                158   POINT(-78.4 28)
12  2018-01-03                168   POINT(-78.3 28)
13  2018-01-03                167   POINT(-78.2 28)
14  2018-01-03                121   POINT(-78.1 28)
15  2018-01-03                 47   POINT(-77.9 28)
16  2018-01-03                 33   POINT(-75.3 27)
17  2018-01-03                 84   POINT(-75.2 27)
18  2018-01-03                235   POINT(-75.1 27)
19  2018-01-03                 98   POINT(-74.9 27)

In [43]:
df

            date  number_of_strikes  center_point_geom
0     2018-01-03                194      POINT(-75 27)
1     2018-01-03                 41    POINT(-78.4 29)
2     2018-01-03                 33    POINT(-73.9 27)
3     2018-01-03                 38    POINT(-73.8 27)
4     2018-01-03                 92      POINT(-79 28)
...          ...                ...                ...
9995  2018-02-07                111  POINT(-91.7 31.5)
9996  2018-02-07                111  POINT(-91.6 31.5)
9997  2018-02-07                 86  POINT(-91.5 31.5)
9998  2018-02-07                101  POINT(-91.4 31.5)
9999  2018-02-07                 85  POINT(-90.4 31.6)

[10000 rows x 3 columns]

In [44]:
df.drop(df.index[10000:3396838], inplace=True)

In [45]:
df.to_csv("data.csv", index=False)

In [ ]:
I deleted these rows because i had to commit to the github and the files size was exceeding 100

In [46]:
df

            date  number_of_strikes  center_point_geom
0     2018-01-03                194      POINT(-75 27)
1     2018-01-03                 41    POINT(-78.4 29)
2     2018-01-03                 33    POINT(-73.9 27)
3     2018-01-03                 38    POINT(-73.8 27)
4     2018-01-03                 92      POINT(-79 28)
...          ...                ...                ...
9995  2018-02-07                111  POINT(-91.7 31.5)
9996  2018-02-07                111  POINT(-91.6 31.5)
9997  2018-02-07                 86  POINT(-91.5 31.5)
9998  2018-02-07                101  POINT(-91.4 31.5)
9999  2018-02-07                 85  POINT(-90.4 31.6)

[10000 rows x 3 columns]

In [47]:
df.drop(df.index[-1] , inplace=True)

In [48]:
df

            date  number_of_strikes  center_point_geom
0     2018-01-03                194      POINT(-75 27)
1     2018-01-03                 41    POINT(-78.4 29)
2     2018-01-03                 33    POINT(-73.9 27)
3     2018-01-03                 38    POINT(-73.8 27)
4     2018-01-03                 92      POINT(-79 28)
...          ...                ...                ...
9994  2018-02-07                104  POINT(-91.9 31.5)
9995  2018-02-07                111  POINT(-91.7 31.5)
9996  2018-02-07                111  POINT(-91.6 31.5)
9997  2018-02-07                 86  POINT(-91.5 31.5)
9998  2018-02-07                101  POINT(-91.4 31.5)

[9999 rows x 3 columns]

In [49]:
df.to_csv("data1.csv", index=False)